name: Aero
version: 1.0
api-version: 1.17
author: Jaren
main: wtf.jaren.aero.spigot.Aero
depend:
  - LuckPerms
softdepend:
  - PlaceholderAPI
  - Vault
  - ViaVersion
  - ProtocolLib

commands:
  opme:
    permission: aero.opme
  acb:
    permission: aero.acb
  gamemode:
    permission: aero.gamemode
    aliases:
      - gm
      - gms
      - gmc
      - gma
      - gmsp